#!/usr/bin/env bash

# Script to populate bugzilla components

# Authors:
# Michael Huang,        June 30 2015
# Christopher Markieta, July  3 2015

set -e

MY_DIR=$(dirname $0)

if [ $(id -u) -ne 0 ]; then
    echo "Permission denied"
    echo "Root privileges are required for running $0."
    exit 1
fi

while read line
do
     first=$(echo $line | cut -f1 -d!)
    second=$(echo $line | cut -f2 -d!)

    "$MY_DIR"/add_component.pl "$first" "$second"
done < "$MY_DIR"/sumlist.txt

